apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    port: 9180
  admin_api_mtls:
    admin_ssl: false

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  
  admin:
    admin_key_required: false
    admin_key:
      - name: "admin"
        key: "edd1c9f034335f136f87ad84b625c8f1"
        role: admin

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091